# Generated by Django 4.2.3 on 2023-07-16 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MallParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('num_entries', models.IntegerField(blank=True, default=3)),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=10, default=40, max_digits=19)),
                ('exceed_rate', models.DecimalField(blank=True, decimal_places=10, default=5000, max_digits=19)),
                ('flatRate_duration', models.IntegerField(blank=True, default=10800)),
                ('exceed_duration', models.IntegerField(blank=True, default=86400)),
                ('return_duration', models.IntegerField(blank=True, default=1800)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('distances', models.TextField()),
                ('mall_parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.mallparking')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingSlotSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('continuous_rate', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('plate_number', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=4)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_flat_rate', models.BooleanField(default=True)),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='parking_slot_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingslotsize'),
        ),
    ]
