# Generated by Django 4.2.3 on 2023-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('parking', '0002_vehicleparking_entry_index'), ('parking', '0003_remove_vehicleparking_is_flat_rate')]

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleparking',
            name='entry_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='vehicleparking',
            name='is_flat_rate',
        ),
    ]
