# Generated by Django 4.2.3 on 2023-07-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_vehicleparking_entry_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleparking',
            name='is_flat_rate',
        ),
    ]
