# Generated by Django 4.2.3 on 2023-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_vehicleparking_entry_index_squashed_0003_remove_vehicleparking_is_flat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
