# Generated by Django 4.2.3 on 2023-07-18 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_vehicleparking_entry_index_squashed_0006_alter_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='vehicle_parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.vehicleparking'),
        ),
    ]
